// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtestpr.h"

extern XTestpr_Config XTestpr_ConfigTable[];

XTestpr_Config *XTestpr_LookupConfig(u16 DeviceId) {
	XTestpr_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTESTPR_NUM_INSTANCES; Index++) {
		if (XTestpr_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTestpr_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTestpr_Initialize(XTestpr *InstancePtr, u16 DeviceId) {
	XTestpr_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTestpr_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTestpr_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

